### ISSUE TITLE
Usage of 'anticheat' more consistent

### ISSUE THREAD

**Issue by missionarydev** [HawkAnticheat/hawkanticheat.github.io#2]
The usage of 'anticheat'/'anti-cheat' need to be more consistent. 
Example:
![image](https://user-images.githubusercontent.com/18586373/45856395-2224ea00-bd09-11e8-8337-6b2084865f48.png)

@Islandscout What is the proper term that you want to use?

**Comment by Islandscout** [comment]
I think "anticheat" will do fine.
